#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : libinput
Version  : 20.06.18
Release  : 3
URL      : /insilications/build/clearlinux/packages/libinput/libinput-20.06.18.zip
Source0  : /insilications/build/clearlinux/packages/libinput/libinput-20.06.18.zip
Summary  : Input device library
Group    : Development/Tools
License  : GPL-2.0
Requires: libinput-bin = %{version}-%{release}
Requires: libinput-config = %{version}-%{release}
Requires: libinput-data = %{version}-%{release}
Requires: libinput-lib = %{version}-%{release}
Requires: libinput-libexec = %{version}-%{release}
Requires: libinput-man = %{version}-%{release}
BuildRequires : buildreq-meson
BuildRequires : doxygen
BuildRequires : graphviz
BuildRequires : graphviz-extras
BuildRequires : pkgconfig(check)
BuildRequires : pkgconfig(fribidi)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(libevdev)
BuildRequires : pkgconfig(libudev)
BuildRequires : pkgconfig(mtdev)
BuildRequires : python3-dev
BuildRequires : valgrind
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
libinput
========
libinput is a library that provides a full input stack for display servers
and other applications that need to handle input devices provided by the
kernel.

%package bin
Summary: bin components for the libinput package.
Group: Binaries
Requires: libinput-data = %{version}-%{release}
Requires: libinput-libexec = %{version}-%{release}
Requires: libinput-config = %{version}-%{release}

%description bin
bin components for the libinput package.


%package config
Summary: config components for the libinput package.
Group: Default

%description config
config components for the libinput package.


%package data
Summary: data components for the libinput package.
Group: Data

%description data
data components for the libinput package.


%package dev
Summary: dev components for the libinput package.
Group: Development
Requires: libinput-lib = %{version}-%{release}
Requires: libinput-bin = %{version}-%{release}
Requires: libinput-data = %{version}-%{release}
Provides: libinput-devel = %{version}-%{release}
Requires: libinput = %{version}-%{release}

%description dev
dev components for the libinput package.


%package lib
Summary: lib components for the libinput package.
Group: Libraries
Requires: libinput-data = %{version}-%{release}
Requires: libinput-libexec = %{version}-%{release}

%description lib
lib components for the libinput package.


%package libexec
Summary: libexec components for the libinput package.
Group: Default
Requires: libinput-config = %{version}-%{release}

%description libexec
libexec components for the libinput package.


%package man
Summary: man components for the libinput package.
Group: Default

%description man
man components for the libinput package.


%prep
%setup -q -n libinput-20.06.18
cd %{_builddir}/libinput-20.06.18

%build
unset http_proxy
unset https_proxy
unset no_proxy
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1594388075
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
## altflags1 content
export CFLAGS="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -fno-common -feliminate-unused-debug-types -fipa-pta -flto=12 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe"
# -ffat-lto-objects -fno-PIE -fno-PIE -m64 -no-pie -fpic -fvisibility=hidden
# gcc: -feliminate-unused-debug-types -fipa-pta -flto=12 -fno-common -Wno-error -Wp,-D_REENTRANT
export CXXFLAGS="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -fno-common -feliminate-unused-debug-types -fipa-pta -flto=12 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -fvisibility-inlines-hidden -pipe"
#
export FCFLAGS="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -fno-common -feliminate-unused-debug-types -fipa-pta -flto=12 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe"
export FFLAGS="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -fno-common -feliminate-unused-debug-types -fipa-pta -flto=12 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe"
export CFFLAGS="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -fno-common -feliminate-unused-debug-types -fipa-pta -flto=12 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe"
#
export LDFLAGS="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -fno-common -feliminate-unused-debug-types -fipa-pta -flto=12 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe"
#
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
#export CCACHE_DISABLE=1
## altflags1 end
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain -Dlibwacom=false -Ddocumentation=false -Ddebug-gui=false  builddir
ninja -v -C builddir

%check
export LANG=C.UTF-8
unset http_proxy
unset https_proxy
unset no_proxy
meson test -C builddir

%install
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)
/usr/lib/udev/libinput-device-group
/usr/lib/udev/libinput-fuzz-extract
/usr/lib/udev/libinput-fuzz-to-zero

%files bin
%defattr(-,root,root,-)
/usr/bin/libinput

%files config
%defattr(-,root,root,-)
/usr/lib/udev/rules.d/80-libinput-device-groups.rules
/usr/lib/udev/rules.d/90-libinput-fuzz-override.rules

%files data
%defattr(-,root,root,-)
/usr/share/libinput/quirks/10-generic-keyboard.quirks
/usr/share/libinput/quirks/10-generic-lid.quirks
/usr/share/libinput/quirks/10-generic-trackball.quirks
/usr/share/libinput/quirks/30-vendor-aiptek.quirks
/usr/share/libinput/quirks/30-vendor-alps.quirks
/usr/share/libinput/quirks/30-vendor-contour.quirks
/usr/share/libinput/quirks/30-vendor-cypress.quirks
/usr/share/libinput/quirks/30-vendor-elantech.quirks
/usr/share/libinput/quirks/30-vendor-ibm.quirks
/usr/share/libinput/quirks/30-vendor-kensington.quirks
/usr/share/libinput/quirks/30-vendor-logitech.quirks
/usr/share/libinput/quirks/30-vendor-madcatz.quirks
/usr/share/libinput/quirks/30-vendor-microsoft.quirks
/usr/share/libinput/quirks/30-vendor-razer.quirks
/usr/share/libinput/quirks/30-vendor-synaptics.quirks
/usr/share/libinput/quirks/30-vendor-trust.quirks
/usr/share/libinput/quirks/30-vendor-vmware.quirks
/usr/share/libinput/quirks/30-vendor-wacom.quirks
/usr/share/libinput/quirks/50-system-acer.quirks
/usr/share/libinput/quirks/50-system-apple.quirks
/usr/share/libinput/quirks/50-system-asus.quirks
/usr/share/libinput/quirks/50-system-chicony.quirks
/usr/share/libinput/quirks/50-system-cyborg.quirks
/usr/share/libinput/quirks/50-system-dell.quirks
/usr/share/libinput/quirks/50-system-google.quirks
/usr/share/libinput/quirks/50-system-hp.quirks
/usr/share/libinput/quirks/50-system-lenovo.quirks
/usr/share/libinput/quirks/50-system-sony.quirks
/usr/share/libinput/quirks/50-system-system76.quirks
/usr/share/libinput/quirks/50-system-toshiba.quirks
/usr/share/zsh/site-functions/_libinput

%files dev
%defattr(-,root,root,-)
/usr/include/libinput.h
/usr/lib64/libinput.so
/usr/lib64/pkgconfig/libinput.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libinput.so.10
/usr/lib64/libinput.so.10.13.0

%files libexec
%defattr(-,root,root,-)
/usr/libexec/libinput/libinput-analyze
/usr/libexec/libinput/libinput-analyze-per-slot-delta
/usr/libexec/libinput/libinput-debug-events
/usr/libexec/libinput/libinput-debug-tablet
/usr/libexec/libinput/libinput-list-devices
/usr/libexec/libinput/libinput-measure
/usr/libexec/libinput/libinput-measure-fuzz
/usr/libexec/libinput/libinput-measure-touch-size
/usr/libexec/libinput/libinput-measure-touchpad-pressure
/usr/libexec/libinput/libinput-measure-touchpad-size
/usr/libexec/libinput/libinput-measure-touchpad-tap
/usr/libexec/libinput/libinput-quirks
/usr/libexec/libinput/libinput-record
/usr/libexec/libinput/libinput-replay

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/libinput-analyze-per-slot-delta.1
/usr/share/man/man1/libinput-analyze.1
/usr/share/man/man1/libinput-debug-events.1
/usr/share/man/man1/libinput-debug-tablet.1
/usr/share/man/man1/libinput-list-devices.1
/usr/share/man/man1/libinput-measure-fuzz.1
/usr/share/man/man1/libinput-measure-touch-size.1
/usr/share/man/man1/libinput-measure-touchpad-pressure.1
/usr/share/man/man1/libinput-measure-touchpad-size.1
/usr/share/man/man1/libinput-measure-touchpad-tap.1
/usr/share/man/man1/libinput-measure.1
/usr/share/man/man1/libinput-quirks-list.1
/usr/share/man/man1/libinput-quirks-validate.1
/usr/share/man/man1/libinput-quirks.1
/usr/share/man/man1/libinput-record.1
/usr/share/man/man1/libinput-replay.1
/usr/share/man/man1/libinput-test-suite.1
/usr/share/man/man1/libinput.1
